name: Karachi AQI CI/CD Pipeline

on:
  schedule:
    - cron: '0 * * * *'   # Hourly features
    - cron: '0 0 * * *'   # Daily training
  workflow_dispatch:

jobs:
  run-aqi-system:
    runs-on: ubuntu-latest

    env:
      MONGO_URI: ${{ secrets.MONGO_URI }}
      DAGSHUB_USER: ${{ secrets.DAGSHUB_USERNAME }}
      DAGSHUB_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Libraries
        run: |
          pip install pandas numpy requests pymongo mlflow joblib scikit-learn certifi jupyter

      # Hourly Feature Pipeline
      - name: Sync Features to MongoDB
        if: (github.event_name == 'schedule' && github.event.schedule == '0 * * * *') || github.event_name == 'workflow_dispatch'
        run: |
          python scripts/extraction.py
          python scripts/features.py
          python scripts/mongodb_connect.py

      # Daily Training Pipeline
      - name: Retrain Random Forest & Register
        if: (github.event_name == 'schedule' && github.event.schedule == '0 0 * * *') || github.event_name == 'workflow_dispatch'
        run: |
          jupyter nbconvert --to python Training_only_randomforest.ipynb
          python Training_only_randomforest.py
          python scripts/register_model_to_dagshub.py
