name: Karachi AQI CI/CD Pipeline

on:
  schedule:
    - cron: '0 * * * *'  # Hourly data sync
    - cron: '0 0 * * *'  # Daily RF training
  workflow_dispatch:      # Manual run button

jobs:
  run-aqi-system:
    runs-on: ubuntu-latest
    
    env:
      MONGO_URI: ${{ secrets.MONGO_URI }}
      DAGSHUB_USERNAME: ${{ secrets.DAGSHUB_USERNAME }}
      DAGSHUB_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Libraries
        run: |
          pip install pandas numpy requests pymongo mlflow dagshub joblib scikit-learn certifi nbconvert

      # Runs hourly
      - name: Sync Features to MongoDB
        if: github.event_name == 'schedule' && github.event.schedule == '0 * * * *' || github.event_name == 'workflow_dispatch'
        run: |
          python scripts/extraction.py
          python scripts/features.py
          python scripts/mongodb_connect.py

      # Runs daily
      - name: Retrain Random Forest & Register
        if: github.event_name == 'schedule' && github.event.schedule == '0 0 * * *' || github.event_name == 'workflow_dispatch'
        run: |
          # Convert Notebook to a Python script first
          jupyter nbconvert --to python Training_only_randomforest.ipynb
          # Run the converted script
          python Training_only_randomforest.py
          # Register to DagsHub
          python scripts/register_model_to_dagshub.py