name: AQI Daily Training Pipeline

on:
  schedule:
    - cron: '0 0 * * *'   # Midnight UTC
  workflow_dispatch:

jobs:
  training:
    runs-on: ubuntu-latest

    env:
      MONGO_URI: ${{ secrets.MONGO_URI }}
      DAGSHUB_USERNAME: ${{ secrets.DAGSHUB_USERNAME }}
      DAGSHUB_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - run: |
          pip install pandas numpy pymongo mlflow joblib scikit-learn jupyter certifi
          jupyter nbconvert --to python Training_only_randomforest.ipynb
          python Training_only_randomforest.py
          python scripts/register_model_to_dagshub.py
